// mf-heterogeneous/mf-cart-react/src/Cart.jsx
import React, { useState, useEffect } from 'react';
import { getCart, removeFromCart, updateCartItemQuantity, clearCart, getCartTotal } from './utils/cart';

function Cart() {
  const [cartItems, setCartItems] = useState([]);

  useEffect(() => {
    // Load initial cart
    setCartItems(getCart());

    // Listen for cart updates from other microfrontends
    const handleCartUpdate = (event) => {
      setCartItems(event.detail);
    };

    window.addEventListener('cartUpdated', handleCartUpdate);

    return () => {
      window.removeEventListener('cartUpdated', handleCartUpdate);
    };
  }, []);

  const handleQuantityChange = (productId, newQuantity) => {
    updateCartItemQuantity(productId, parseInt(newQuantity));
  };

  const handleRemoveItem = (productId) => {
    removeFromCart(productId);
  };

  const handleClearCart = () => {
    if (window.confirm('Are you sure you want to clear your cart?')) {
      clearCart();
    }
  };

  const handleCheckout = () => {
    if (cartItems.length === 0) {
      alert('Your cart is empty!');
      return;
    }
    
    const total = getCartTotal();
    alert(`Thank you for your purchase! Total: $${total.toFixed(2)}`);
    clearCart();
  };

  if (cartItems.length === 0) {
    return (
      <div className="max-w-4xl mx-auto text-center py-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">
          Your Cart (React Remote)
        </h2>
        <div className="bg-gray-100 rounded-lg p-8">
          <p className="text-xl text-gray-600 mb-4">Your cart is empty</p>
          <a
            href="/products"
            className="inline-block bg-blue-500 text-white px-6 py-3 rounded-lg hover:bg-blue-600 transition-colors"
          >
            Continue Shopping
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-3xl font-bold text-gray-800">
          Your Cart (React Remote)
        </h2>
        <button
          onClick={handleClearCart}
          className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition-colors"
        >
          Clear Cart
        </button>
      </div>

      <div className="bg-white rounded-lg shadow-md overflow-hidden">
        <div className="grid grid-cols-1 gap-0">
          {cartItems.map((item) => (
            <div key={item.id} className="flex items-center p-4 border-b border-gray-200 last:border-b-0">
              <img
                src={item.image || `https://via.placeholder.com/80x80?text=${item.name}`}
                alt={item.name}
                className="w-16 h-16 object-cover rounded"
              />
              <div className="flex-1 ml-4">
                <h3 className="text-lg font-semibold text-gray-800">{item.name}</h3>
                <p className="text-blue-600 font-bold">${item.price}</p>
              </div>
              <div className="flex items-center space-x-2">
                <label htmlFor={`quantity-${item.id}`} className="text-sm text-gray-600">
                  Qty:
                </label>
                <input
                  id={`quantity-${item.id}`}
                  type="number"
                  min="1"
                  value={item.quantity}
                  onChange={(e) => handleQuantityChange(item.id, e.target.value)}
                  className="w-16 px-2 py-1 border border-gray-300 rounded text-center"
                />
              </div>
              <div className="ml-4 text-right">
                <p className="text-lg font-bold text-gray-800">
                  ${(item.price * item.quantity).toFixed(2)}
                </p>
                <button
                  onClick={() => handleRemoveItem(item.id)}
                  className="text-red-500 hover:text-red-700 text-sm mt-1"
                >
                  Remove
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="bg-gray-50 p-4">
          <div className="flex justify-between items-center mb-4">
            <span className="text-xl font-bold text-gray-800">Total:</span>
            <span className="text-2xl font-bold text-blue-600">
              ${getCartTotal().toFixed(2)}
            </span>
          </div>
          <div className="flex space-x-4">
            <a
              href="/products"
              className="flex-1 bg-gray-500 text-white text-center py-3 px-4 rounded hover:bg-gray-600 transition-colors"
            >
              Continue Shopping
            </a>
            <button
              onClick={handleCheckout}
              className="flex-1 bg-green-500 text-white py-3 px-4 rounded hover:bg-green-600 transition-colors"
            >
              Checkout
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Cart;

// mf-heterogeneous/mf-cart-svelte/src/Cart.svelte
<script>
  import { onMount } from "svelte";
  import { getCart, addToCart, removeFromCart } from "./utils/cart.js";

  let cart = {};
  let products = [];
  let total = 0;

  onMount(() => {
    updateCart();
  });

  function updateCart() {
    cart = getCart();
    products = Object.values(cart).filter(Boolean);
    total = products.reduce(
      (sum, p) => sum + (p.price || 0) * (p.quantity || 0),
      0
    );
  }

  function handleAdd(product) {
    addToCart(product);
    updateCart();
  }

  function handleRemove(id) {
    removeFromCart(id);
    updateCart();
  }

  function clearCart() {
    localStorage.setItem("cart", JSON.stringify({}));
    updateCart();
  }
</script>

<div class="max-w-4xl mx-auto px-4 py-8">
  <!-- Header -->
  <div class="flex items-center justify-between mb-8">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Shopping Cart</h1>
      <p class="text-gray-600 mt-1">
        {products.length === 0
          ? "Your cart is empty"
          : `${products.length} ${products.length === 1 ? "item" : "items"} in your cart`}
      </p>
    </div>
    <a
      href="/"
      class="inline-flex items-center px-4 py-2 text-sm font-medium text-blue-700 bg-blue-50 rounded-lg hover:bg-blue-100 transition-colors duration-200"
    >
      <svg
        class="w-4 h-4 mr-2"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M10 19l-7-7m0 0l7-7m-7 7h18"
        />
      </svg>
      Continue Shopping
    </a>
  </div>

  {#if products.length === 0}
    <div class="text-center py-16">
      <div
        class="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6"
      >
        <svg
          class="w-10 h-10 text-gray-400"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="1.5"
            d="M3 3h2l.4 2M7 13h10l4-8H5.4m2.6 8L6 5H3m4 8v4a2 2 0 002 2h8a2 2 0 002-2v-4"
          />
        </svg>
      </div>
      <h3 class="text-lg font-medium text-gray-900 mb-2">Your cart is empty</h3>
      <p class="text-gray-500 mb-6">Add some products to get started</p>
      <a
        href="/"
        class="inline-flex items-center px-6 py-3 bg-blue-700 text-white font-medium rounded-xl hover:bg-blue-800 transition-colors duration-200"
      >
        <svg
          class="w-5 h-5 mr-2"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M3 3h2l.4 2M7 13h10l4-8H5.4m2.6 8L6 5H3m4 8v4a2 2 0 002 2h8a2 2 0 002-2v-4"
          />
        </svg>
        Start Shopping
      </a>
    </div>
  {:else}
    <div class="space-y-6">
      <!-- Cart Items -->
      <div class="bg-white rounded-2xl border border-gray-100 overflow-hidden">
        {#each products as item, index (item.id)}
          <div
            class="p-6 flex items-start space-x-4 {index !== products.length - 1
              ? 'border-b border-gray-100'
              : ''}"
          >
            <!-- Product Image -->
            <div
              class="w-20 h-20 bg-gray-50 rounded-xl flex items-center justify-center flex-shrink-0"
            >
              <img
                src={item.image}
                alt={item.title}
                class="w-10 h-10 object-contain"
              />
            </div>

            <!-- Product Info -->
            <div class="flex-1 min-w-0">
              <h3
                class="font-semibold text-gray-900 text-sm leading-tight line-clamp-2 mb-2"
              >
                {item.title}
              </h3>
              <div class="flex items-center justify-between">
                <div class="text-lg font-bold text-blue-700">
                  ${item.price}
                </div>
                <div class="text-sm text-gray-500">
                  ${(item.price * item.quantity).toFixed(2)}
                </div>
              </div>
            </div>

            <!-- Quantity Controls -->
            <div
              class="flex items-center space-x-3 bg-gray-50 rounded-full p-1 flex-shrink-0"
            >
              <button
                on:click={() => handleRemove(item.id)}
                class="w-8 h-8 rounded-full bg-white shadow-sm border border-gray-200 flex items-center justify-center text-blue-700 hover:bg-blue-50 hover:border-blue-200 transition-all duration-200"
              >
                <svg
                  class="w-4 h-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M20 12H4"
                  />
                </svg>
              </button>
              <span
                class="font-semibold text-blue-700 min-w-[24px] text-center"
              >
                {item.quantity}
              </span>
              <button
                on:click={() => handleAdd(item)}
                class="w-8 h-8 rounded-full bg-blue-700 shadow-sm flex items-center justify-center text-white hover:bg-blue-800 transition-all duration-200"
              >
                <svg
                  class="w-4 h-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M12 4v16m8-8H4"
                  />
                </svg>
              </button>
            </div>
          </div>
        {/each}
      </div>

      <!-- Cart Summary -->
      <div
        class="bg-gradient-to-r from-blue-50 to-blue-100 rounded-2xl p-6 border border-blue-200"
      >
        <div class="flex items-center justify-between mb-4">
          <span class="text-lg font-semibold text-gray-900">Total</span>
          <span class="text-2xl font-bold text-blue-700"
            >${total.toFixed(2)}</span
          >
        </div>

        <!-- Action Buttons - Minimalist and Small -->
        <div class="flex space-x-3">
          <button
            on:click={clearCart}
            class="px-4 py-2 text-sm font-medium text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 hover:border-gray-300 transition-all duration-200"
          >
            Clear Cart
          </button>
          <button
            class="flex-1 bg-blue-700 hover:bg-blue-800 text-white font-medium py-2 px-4 rounded-lg transition-all duration-200 flex items-center justify-center space-x-2 text-sm group"
          >
            <svg
              class="w-4 h-4 group-hover:scale-110 transition-transform"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M5 13l4 4L19 7"
              />
            </svg>
            <span>Proceed to Checkout</span>
          </button>
        </div>
      </div>
    </div>
  {/if}
</div>
